[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "inventario2"
authors = [{name = "Ricardo Montañana", email = "rmontanana@gmail.com"}]
dynamic = ["version", "description"]
